services:
    db:
        image: mysql:8.0
        platform: linux/arm64
        container_name: filmoteca_db
        volumes:
            - "filmoteca_db_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        ports:
            - "3306:3306"
        networks:
            - filmoteca_network

    adminer:
        image: adminer
        platform: linux/arm64
        container_name: filmoteca_adminer
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: filmoteca_db
            ADMINER_DEFAULT_DB_NAME: ${MYSQL_DATABASE}
            ADMINER_DEFAULT_SERVER: filmoteca_db
        restart: always
        ports:
            - "127.0.0.1:8081:8080"
        depends_on:
            - db
        networks:
            - filmoteca_network

    php:
        container_name: filmoteca_php
        platform: linux/arm64
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/filmoteca:cached
        networks:
            - filmoteca_network

    nginx:
        container_name: filmoteca_nginx
        platform: linux/arm64
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/filmoteca:cached
        ports:
            - "80:80"
        networks:
            - filmoteca_network
        env_file:
            - .env.nginx
        depends_on:
            - php

    mailhog:
        image: mailhog/mailhog
        container_name: filmoteca_mailhog
        ports:
            - "2525:1025"
            - "8090:8025"
        networks:
            - filmoteca_network

volumes:
    filmoteca_db_data:

networks:
    filmoteca_network:
